# Generated by Django 4.2.1 on 2023-05-10 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="Task",
            name="file",
            field=models.FileField(upload_to="documents/"),
        ),
    ]
